SELECT
	`NAME`
FROM
	`USER`
WHERE
	`NAME` NOT LIKE 'u_%'
AND `NAME` NOT LIKE '\_%'
AND `NAME` NOT LIKE '201%'
AND LENGTH(`NAME`) < 13
AND NAME NOT LIKE 'a%'
AND NAME NOT LIKE '0%'
AND NAME NOT LIKE '1%'
AND NAME NOT LIKE '2%'
AND NAME NOT LIKE '3%'
AND NAME NOT LIKE '4%'
AND NAME NOT LIKE '5%'
AND NAME NOT LIKE '6%'
AND NAME NOT LIKE '7%'
AND NAME NOT LIKE '8%'
AND NAME NOT LIKE '9%'
AND NAME NOT LIKE 'ty\_%'
AND NAME NOT LIKE 'zy%'
AND NAME NOT LIKE 'yy%'
AND LENGTH(`NAME`) > 4
GROUP BY
	`NAME`;

	--- 爬取用户昵称后的过滤